workspace:
  base: /go
  path: src/github.com/wyattjoh/ims

pipeline:
  test:
    image: golang:1.8
    environment:
      - CGO_ENABLED=0
    commands:
      - go vet
      - go test -cover -coverprofile=coverage.out
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER" -a -tags netgo

  publish:
    image: plugins/docker
    repo: wyattjoh/ims
    password: ${DOCKER_PASSWORD}
    email: ${DOCKER_EMAIL}
    username: ${DOCKER_USERNAME}
    tags: [ "latest" ]
    when:
      branch: master
      event: push