sudo: required

language: go
go:
  - 1.9

services:
  - docker

script:
  - bash ./scripts/test.sh

after_success:
  - docker build -t wyattjoh/ims .
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push wyattjoh/ims;
    fi